data = [
    {"name": "Rihanna", "follower_count": 150, "description": "Musician and businesswoman", "country": "Barbados"},
    {"name": "Zendaya", "follower_count": 180, "description": "Actress and musician", "country": "USA"},
    {"name": "Cristiano Ronaldo", "follower_count": 650, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 500, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 420, "description": "Singer and actress", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Reality TV star", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": 390, "description": "Actor and wrestler", "country": "USA"},
    {"name": "Ariana Grande", "follower_count": 380, "description": "Singer", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 360, "description": "Reality TV personality", "country": "USA"},
    {"name": "Beyoncé", "follower_count": 310, "description": "Singer", "country": "USA"},
    {"name": "Justin Bieber", "follower_count": 290, "description": "Singer", "country": "Canada"},
    {"name": "Taylor Swift", "follower_count": 280, "description": "Singer-songwriter", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 270, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "follower_count": 250, "description": "Singer and actress", "country": "USA"},
    {"name": "Nicki Minaj", "follower_count": 230, "description": "Rapper", "country": "USA"},
    {"name": "Miley Cyrus", "follower_count": 210, "description": "Singer and actress", "country": "USA"},
    {"name": "Neymar", "follower_count": 220, "description": "Footballer", "country": "Brazil"},
    {"name": "Shakira", "follower_count": 200, "description": "Singer", "country": "Colombia"},
    {"name": "Billie Eilish", "follower_count": 190, "description": "Singer", "country": "USA"},
    {"name": "Drake", "follower_count": 180, "description": "Rapper", "country": "Canada"},
    {"name": "LeBron James", "follower_count": 170, "description": "Basketball player", "country": "USA"},
    {"name": "Kevin Hart", "follower_count": 160, "description": "Comedian", "country": "USA"},
    {"name": "Chris Hemsworth", "follower_count": 150, "description": "Actor", "country": "Australia"},
    {"name": "Ellen DeGeneres", "follower_count": 140, "description": "TV host", "country": "USA"},
    {"name": "NASA", "follower_count": 100, "description": "Space agency", "country": "USA"},
    {"name": "National Geographic", "follower_count": 280, "description": "Magazine", "country": "USA"},
    {"name": "Nike", "follower_count": 300, "description": "Sportswear brand", "country": "USA"},
    {"name": "Adidas", "follower_count": 280, "description": "Sportswear brand", "country": "Germany"},
    {"name": "FC Barcelona", "follower_count": 120, "description": "Football club", "country": "Spain"},
    {"name": "Real Madrid", "follower_count": 140, "description": "Football club", "country": "Spain"},
    {"name": "Champions League", "follower_count": 110, "description": "Football competition", "country": "Europe"},
    {"name": "Marvel", "follower_count": 200, "description": "Entertainment company", "country": "USA"},
    {"name": "Netflix", "follower_count": 220, "description": "Streaming service", "country": "USA"},
    {"name": "YouTube", "follower_count": 350, "description": "Video platform", "country": "USA"},
    {"name": "Instagram", "follower_count": 670, "description": "Social media platform", "country": "USA"},
    {"name": "TikTok", "follower_count": 800, "description": "Social media platform", "country": "China"},
    {"name": "Elon Musk", "follower_count": 200, "description": "Entrepreneur", "country": "USA"},
    {"name": "Mark Zuckerberg", "follower_count": 120, "description": "Facebook founder", "country": "USA"},
    {"name": "Bill Gates", "follower_count": 130, "description": "Microsoft co-founder", "country": "USA"},
    {"name": "Jeff Bezos", "follower_count": 140, "description": "Amazon founder", "country": "USA"},
    {"name": "Google", "follower_count": 250, "description": "Tech company", "country": "USA"},
    {"name": "Apple", "follower_count": 300, "description": "Tech company", "country": "USA"},
    {"name": "Microsoft", "follower_count": 280, "description": "Tech company", "country": "USA"},
    {"name": "Amazon", "follower_count": 260, "description": "E-commerce company", "country": "USA"},
    {"name": "OpenAI", "follower_count": 150, "description": "AI research lab", "country": "USA"}
]